### ISSUE TITLE
How to create a trimmer View in a new UIViewController.

### ISSUE THREAD

**Issue by ajay2c9** [prynt/PryntTrimmerView#15]
![screen shot 2017-10-17 at 7 07 32 pm](https://user-images.githubusercontent.com/9112899/31668101-eaf3a17e-b36e-11e7-85d1-29b690de4547.png)
![screen shot 2017-10-17 at 7 09 58 pm](https://user-images.githubusercontent.com/9112899/31668115-f35bdebc-b36e-11e7-991b-021a76107354.png)

I want to create a trimmer View in a new view controller. I created a new view controller in the sample project and one view and a trimmerView in viewController. I have few doubt in this.

1. In storyboard while assigning the class to the view(brown view) Class name is display as trimmerView but while creating outlets in file trimmerView is not displaying. it is displaying as PryntTrimmerView and connection is not applicable to that view.

2. I tried to create dynamically but the properties
trimmerView.asset = asset
trimmerView.delegate = self
 trimmerView.handleColor = UIColor.white
trimmerView.mainColor = UIColor.orange
trimmerView.positionBarColor = UIColor.white

are not calling and not displaying in view controller.
Please give suggestion to implement the Trimmerview in UiViewController and can use the properties and delegate methods  to trim the video.

Thank you

**Comment by HHK1** [comment]
@ajay2c9 With your screenshots I'm noticing two things that can cause this.

1. There seems to be no outlets on your TrimmerView in the second screenshots. If you right-click on your view in your storyboard, you should see one referencing outlet. If not, make sure to recreate your outlet correctly.

2. In the second screenshot still, in the right pane: You can see that the designable status indicates "Build failed". It means that the PryntTrimmerView module did not compile correctly. Make sure it's building correctly. The example project uses cocoapod, so if you decided to change the version (as you should since you're not using Xcode 9), make sure to run `pod install` in the root of the example project before.

**Comment by ajay2c9** [comment]
I tried lot of times but same issue is raising. I updated the pod in sample project to 1.0.1 version.  "Build failed" is displaying.  please give suggestion to implement the trimmerView using the xib or dynamically.
Thank you.

**Comment by HHK1** [comment]
> please give suggestion to implement the trimmerView using the xib or dynamically.

If the pod is not building, that's not going to work either. Please make sure to follow those steps.

1. Clone the project from fresh again: `git clone git@github.com:prynt/PryntTrimmerView.git`
2. Change the version: "git checkout 1.0.1'
3. Inside the example folder, run `pod install`
4. Change the active scheme to the Pod (not the Example App), and build it.
 
You should successfully build it at that point. Then, you can retry creating outlets in the storyboard.

**Comment by ajay2c9** [comment]
Thank you for suggestion. pod is successfully installed and outlets are applied.Frames are displaying in the trimmer View. I am facing a problem here i.e position bar is not moving please give suggestion to move the position bar

**Comment by HHK1** [comment]
Please open a new issue if you’re having trouble with a different topic. 
If your first issue is resolved, then you can close it. 
Also, try to add all the relevant information when creating an issue: What are you trying to achieve, what is happening instead ? The more information you give, the more I’ll be able to help you.

**Comment by ajay2c9** [comment]
Ok
