### ISSUE TITLE
Crash in regenerateThumbnails(for asset: AVAsset)

### ISSUE THREAD

**Issue by NikKovIos** [prynt/PryntTrimmerView#20]
`let visibleThumbnailsCount = Int(ceil(frame.width / thumbnailSize.width))`  line gives a crash

![2018-04-18 21 15 55](https://user-images.githubusercontent.com/16647690/38950312-b61e3dfa-434d-11e8-954f-15c11c22af98.png)

Before this the AVAssetTimeSelector.frame gives (30.0, 88.0, 315.0, 56.0), but assetPreview.frame gives (0.0, 0.0, 0.0, 0.0).
I think the problem is with frames.

**Comment by HHK1** [comment]
Do you have more elements please ?
The stack trace, steps to reproduce and an example project could help a lot

**Comment by NikKovIos** [comment]
I've uploaded this here https://github.com/Yummypets/YPImagePicker/commit/4fea39d9c3688a1ea8e36ae83dcce59a507c3e3d

Just clone repo and move to this commit state.

**Comment by HHK1** [comment]
First thing you can do is check the `thumbnailSize.width` and add a guard close to check it's not zero, it will prevent the crash

Now, the real issue is before. The thumbnailSize is based on the video track naturalSize. If the track or its size is not loaded, it will return a size of `.zero`

Are you using remote assets ? If so, are you sure that all the values are correctly loaded ? You can use `loadValuesAsynchronously(forKeys: , completionHandler:)` on your AVAsset to do so.

**Comment by NikKovIos** [comment]
I use assets from the device. Also i checked the same asset in your library's example and it didn't crash. I mean i took the asset URL (file://root/file.mov) and tried in example, then tried in my project.
```swift
let asset2 = AVAsset(url: URL(fileURLWithPath: "file:///var/mobile/Media/DCIM/100APPLE/IMG_0068.MOV"))
        trimmerView.asset = asset2
```

Also when i did change in AVAssetTimeSelector

```
public override func layoutSubviews() {
        assetPreview.frame = frame
        super.layoutSubviews()
    }

func setupSubviews() {
        setupAssetPreview()
        layoutSubviews()
//        constrainAssetPreview()
    }
```
there is next picture:
![screen shot 2018-04-19 at 13 56 46](https://user-images.githubusercontent.com/16647690/38987773-9f4a8390-43d9-11e8-9ba4-2fa7dd10d538.png)

**Comment by HHK1** [comment]
If you start removing constraints, that's not going to help.
In the `getThumbnailFrameSize(from asset: AVAsset)` what's the frame at that point ? If it's zero, then you won't know what the thumbnail size is supposed to be. I can add some safeguards here, but in the end, your constraints are just broken

I've no idea what you are trying to achieve regarding #21 and what you are showing me with your constraints ? What was the goal of this in the first place ?

**Comment by NikKovIos** [comment]
The goal of this is to make it work!) Did you look at the example? Do you see, that constraints are well in YPVideoFiltersVC, but the PryntTrimmerView is broken, the getThumbnailFrameSize gives zero?  
I just want to make it work.

**Comment by HHK1** [comment]
>The goal of this is to make it work!) Did you look at the example? Do you see, that constraints are well in YPVideoFiltersVC, but the PryntTrimmerView is broken? The getThumbnailFrameSize gives zero. 

I looked at your code, and I saw that you copied the source files, and commented out the constraints. Which led me to ask you: What are you trying to achieve by removing the constraints or overriding them ?

> Help please to find out what is the reason of this.

Your project is big. If you need help to pinpoint the issue, please make a small, minimal example to reproduce the issue, with clean dependencies. A fork of this library is a good start.

>In my example the trimmer view frame is (30.0, 77.5, 315.0, 77.0) - it supposed to be it. AssetSize in getThumbailFrameSize is (width = -1080, height = 1920), but the frame.height is zero. So the width and the ratio is zero too.

Ok, so if the frame.height is zero, why don't you keep the constraints as is, and see what happens ?
Also, I pushed a commit on master to add a safeguard so that it does not crash if you want to give it a try.

**Comment by NikKovIos** [comment]
Here is the project
[TestTrim.zip](https://github.com/prynt/PryntTrimmerView/files/1935369/TestTrim.zip)

**Comment by NikKovIos** [comment]
When i did paste the asset setting code into dispatch with delay

```swift
       DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 3) {
            let url = URL(fileURLWithPath: "file:///var/mobile/Media/DCIM/100APPLE/IMG_0068.MOV")
            let asset2 = AVAsset(url: url)
            self.trimmerView.asset = asset2
            self.trimmerView.delegate = self
        }
```

Everything start working. It seems, that in viewDidLoad the library is still calculating height value.

**Comment by HHK1** [comment]
Hey, I was not available this weekend, could not reply until now. 

When using constraints, it’s indeed not advised to rely on the frame in the viewDidLoad. You have to wait for viewDidLayoutSubviews for the frame to be calculated. 

I do not advise to use a dispatch in the view did load, you should do this later in the lifecycle of the view controller instead. 

Anyway, I’m glad you found a solution for this.
